fixing yaml

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -7,8 +7,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-python-version: ["3.9"]
-
+        python-version: ["3.9"]
     steps:
     - uses: actions/checkout@v4
     - name: Set up Python ${{ matrix.python-version }}
@@ -20,21 +19,21 @@ python-version: ["3.9"]
         python -m pip install --upgrade pip
         pip install pylint
         pip install -r requirements.txt
-        - name: Run Pylint and calculate score
-        id: pylint
-        run: |
-          # Run Pylint and output the score
-          pylint $(git ls-files '*.py') > pylint_output.txt || true
-          # Extract the score from Pylint output
-          score=$(grep "Your code has been rated at" pylint_output.txt | awk '{print $7}' | cut -d'/' -f1)
-          echo "Pylint score: $score"
-          echo "score=$score" >> $GITHUB_ENV
-      - name: Approve or fail the build
-        run: |
-          echo "Checking Pylint score..."
-          if (( $(echo "$score >= 8" | bc -l) )); then
-            echo "Build approved! Pylint score is $score."
-          else
-            echo "Build failed! Pylint score is $score. Minimum required is 8."
-            exit 1
-          fi
+    - name: Run Pylint and calculate score
+      id: pylint
+      run: |
+        # Run Pylint and output the score
+        pylint $(git ls-files '*.py') > pylint_output.txt || true
+        # Extract the score from Pylint output
+        score=$(grep "Your code has been rated at" pylint_output.txt | awk '{print $7}' | cut -d'/' -f1)
+        echo "Pylint score: $score"
+        echo "score=$score" >> $GITHUB_ENV
+    - name: Approve or fail the build
+      run: |
+        echo "Checking Pylint score..."
+        if (( $(echo "$score >= 8" | bc -l) )); then
+          echo "Build approved! Pylint score is $score."
+        else
+          echo "Build failed! Pylint score is $score. Minimum required is 8."
+          exit 1
+        fi
